name: Tests

on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  test_powershell:
    name: WindowsPowerShell
    runs-on: windows-latest
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@main
        with:
          fetch-depth: 2
          path: my_bucket
      - name: Checkout Scoop
        uses: actions/checkout@main
        with:
          repository: ScoopInstaller/Scoop
          path: scoop_core
      - name: Init Test Suite
        uses: potatoqualitee/psmodulecache@main
        with:
          modules-to-cache: BuildHelpers
          shell: powershell
        env:
          URL: https://github.com/Twometer/NoFences/releases/download/v1.8/NoFences.exe
      - name: Test Bucket
        working-directory: my_bucket
        shell: powershell
        run: |
          $env:SCOOP_HOME="$(Convert-Path '..\scoop_core')"
          .\bin\test.ps1
  test_pwsh:
    name: PowerShell
    runs-on: windows-latest
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@main
        with:
          fetch-depth: 2
          path: my_bucket
      - name: Checkout Scoop
        uses: actions/checkout@main
        with:
          repository: ScoopInstaller/Scoop
          path: scoop_core
      - name: Init Test Suite
        uses: potatoqualitee/psmodulecache@main
        with:
          modules-to-cache: BuildHelpers
          shell: pwsh
        env:
          URL: https://github.com/Twometer/NoFences/releases/download/v1.8/NoFences.exe
      - name: Test Bucket
        working-directory: my_bucket
        shell: pwsh
        run: |
          $env:SCOOP_HOME="$(Convert-Path '..\scoop_core')"
          .\bin\test.ps1
